### ISSUE TITLE
你好，就文本情感分类的问题，想咨询一下

### ISSUE THREAD

**Issue by duxiansheng123** [syuoni/text-sentiment-classification#1]
看到你是用RNN，LSTM，CNN进行的情感分类，但有些问题想要请教一下：对什么文本进行的情感分类，对于文本是怎么处理的，还有各种方法的分类精度如何，想做情感分类方面的研究，还请指导一下

**Comment by syuoni** [comment]
语料说明、处理方法、imdb 的分类结果已经补充。
